[package]
name = "simple-rs"
version = "0.1.0"
authors = ["Christian Blades <cblades@pindrop.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
